### ISSUE TITLE
Signed Banana replaced by King Banana (Keysanity) v25.2

### ISSUE THREAD

**Issue by fxbx** [stochaztic/eb-randomizer#3]
Keysanity on v25.2. I cannot continue because I've gotten two King Bananas and it looks like one should've been the Signed Banana.

The JSON spoiler says that Paula should've given me the Signed Banana at Peaceful Rest but she gave me a King Banana instead. Venus gave me the 2nd King Banana, which according to the JSON should have happened.

I've done some events out of order but this shouldn't influence the key item mix here, or would it? I can probably remember the order if I had to.

My .SMC name is eb.bcd3g2im2suk.64711451

.JSON spoiler attached.

**Comment by fxbx** [comment]
[eb.bcd3g2im2suk.64711451.spoiler.json.txt](https://github.com/pickfifteen/eb-randomizer/files/2343764/eb.bcd3g2im2suk.64711451.spoiler.json.txt)

**Comment by stochaztic** [comment]
Thanks for the bug report, was able to track it down and resolve. Sorry about your interrupted run, hope you continue to enjoy Keysanity!
