### ISSUE TITLE
Teleport to north onett? (KEYSANITY)

### ISSUE THREAD

**Issue by DNVIC** [stochaztic/eb-randomizer#5]
Once  I beat the clumsy robot in fourside, I got teleported to north onett for some reason.

Gameplay path: 

Beat sharks

Talk to the mayor

Give the diamond to the person in the Topolla Theater

Add Jeff to the party (and paula since the game thinks you have her)

Beat Belch

Beat the trillionage sprout

Beat Shrooom!

Beat the 5 moles in Dusty Dunes Desert

Paula gets kidnapped

Beat Mani Mani

Attempt to get myself through the monkey cave and get stuck on the king banana

Give the shyness book to the tenda

Beat the electro specter

Beat the Starman DX

Get stuck again in the monkey cave needing the Pencil Eraser

Get Poo (also gets paula back)

Get the Hawk Eye in the Pyramid

Get the Pencil Eraser

Beat Barf to get Poo back

Beat the clumsy robot

Teleport to North Onett

Seed: 55713725

I know I don't need to do solo jeff, I didn't realize you needed to talk to someone besides the woman in the stoic club to get magic cakes.

Spoiler attached
[eb.bcd3g2im3suk.55713725.spoiler.json.txt](https://github.com/pickfifteen/eb-randomizer/files/2498653/eb.bcd3g2im3suk.55713725.spoiler.json.txt)

**Comment by stochaztic** [comment]
At the end of the Clumsy Robot fight, did it do the "black smoke" text or the "Runaway 5" text?

**Comment by DNVIC** [comment]
Runaway 5 text

**Comment by stochaztic** [comment]
Closed due to Keysanity being removed.
