### ISSUE TITLE
main menu background stops animating when canceling on "are you sure?"

### ISSUE THREAD

**Issue by codl** [stochaztic/eb-randomizer#7]
When creating a new game and when on the final screen, the one that shows all the names and asks "Are you sure?", if I choose "Nope" or press B, the battle background stops animating

This is super minor but I thought I should mention it anyway

**Comment by stochaztic** [comment]
Yes, this is actually a bug in the vanilla game that goes unnoticed because the vanilla naming screen background does not animate. I will consider fixing vanilla bugs, but this one is inconsequential enough I think I'm just going to leave it as is. Thanks for the report!

**Comment by codl** [comment]
fair enough, thank you for the response!
