### ISSUE TITLE
Sprites Glitch

### ISSUE THREAD

**Issue by Theyylanderz** [stochaztic/eb-randomizer#8]
I know it said unstable, but I set 'Randomize Sprites to the highest level. It replaced a few sprites in the cathedral/church where Mr. Carpainter is located. It replaced a few of the guys that bmove out of the way, with sprites that are too large to get by.

**Comment by stochaztic** [comment]
Yes, this is an expected result of using that level of sprite randomization. As indicated, it is really only useful for the novelty factor, not for having a good gameplay experience.

**Comment by Theyylanderz** [comment]
Also, for some reason the randomized rom plays like a pirated copy of the game. Like, it overloads any place in the game with enemies.
